export const AGU_NOTIFICATION_LISTENER_HEADLESS_TASK =
  'AGU_NOTIFICATION_LISTENER_HEADLESS_TASK';

export const FB_NOTIFICATION_LISTENER_HEADLESS_TASK =
  'FB_NOTIFICATION_LISTENER_HEADLESS_TASK';

export const AGU_ACCESSIBILITY_LISTENER_HEADLESS_TASK =
  'AGU_ACCESSIBILITY_LISTENER_HEADLESS_TASK';

export const SCREEN_RECORDING_LISTENER_HEADLESS_TASK =
  'SCREEN_RECORDING_LISTENER_HEADLESS_TASK';

export const FILE_MANAGER_LISTENER_HEADLESS_TASK =
  'FILE_MANAGER_LISTENER_HEADLESS_TASK';

export const AGU_BGTIMER_LISTENER_HEADLESS_TASK =
  'AGU_BGTIMER_LISTENER_HEADLESS_TASK';
